import Foundation
import Testing
import GRDB
@testable import Regards

/// Migration coverage for fresh latest-schema databases and upgrades from the
/// shipped v1 schema (ARCHITECTURE.md §7).
struct DatabaseMigratorTests {

    @Test("Latest migration creates every expected table")
    func latestTables() async throws {
        let db = try DatabaseFactory.makeInMemoryDatabase()
        let tables = try await db.read { db -> Set<String> in
            let sql = """
                SELECT name FROM sqlite_master
                WHERE type = 'table'
                  AND name NOT LIKE 'sqlite_%'
                  AND name NOT LIKE 'grdb_%'
                """
            let names = try String.fetchAll(db, sql: sql)
            return Set(names)
        }
        let expected: Set<String> = [
            "Contact", "ContactGroup", "ReminderWindow",
            "ScheduledReminder", "InteractionLog", "UserProfile",
        ]
        #expect(expected.isSubset(of: tables),
                "missing tables: \(expected.subtracting(tables))")
    }

    @Test("Latest migration preserves the indexes §7 requires")
    func latestIndexes() async throws {
        let db = try DatabaseFactory.makeInMemoryDatabase()
        let indexes = try await db.read { db -> Set<String> in
            let names = try String.fetchAll(db,
                sql: "SELECT name FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%'")
            return Set(names)
        }
        // Index names are auto-generated by GRDB; we just assert one exists
        // covering each required column pair by querying SQLite's index_list.
        let contactIndexes = try await db.read { db -> [String] in
            try Row.fetchAll(db, sql: "PRAGMA index_list('Contact')").map { $0["name"] as String }
        }
        let reminderIndexes = try await db.read { db -> [String] in
            try Row.fetchAll(db, sql: "PRAGMA index_list('ScheduledReminder')").map { $0["name"] as String }
        }
        #expect(!contactIndexes.isEmpty)
        #expect(!reminderIndexes.isEmpty)
        // Ensure the uniqueness on systemContactRef shows up.
        #expect(indexes.contains(where: { $0.contains("Contact") }))
    }

    @Test("Singleton rows are seeded by the migrator")
    func singletonRowsSeeded() async throws {
        let db = try DatabaseFactory.makeInMemoryDatabase()
        let (windowCount, profileCount) = try await db.read { db -> (Int, Int) in
            let w = try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM ReminderWindow") ?? 0
            let p = try Int.fetchOne(db, sql: "SELECT COUNT(*) FROM UserProfile") ?? 0
            return (w, p)
        }
        #expect(windowCount == 1)
        #expect(profileCount == 1)
    }
}

extension DatabaseMigratorTests {
    @Test("File-backed production environment creates protected migrated repositories and reopens")
    func fileBackedEnvironmentCreatesProtectedStorageAndReopens() async throws {
        let fileManager = FileManager.default
        let root = fileManager.temporaryDirectory
            .appendingPathComponent("RegardsDatabaseFactory-\(UUID().uuidString)", isDirectory: true)
        try fileManager.createDirectory(at: root, withIntermediateDirectories: true)
        // Best-effort teardown must not replace a more useful migration or
        // persistence failure with a temporary-directory cleanup error.
        defer { try? fileManager.removeItem(at: root) }

        let fileName = "production-path.sqlite"
        let databaseURL = root
            .appendingPathComponent("Regards", isDirectory: true)
            .appendingPathComponent(fileName)
        let onboardingDate = Date(timeIntervalSince1970: 1_800_000_000)
        let contact = Contact(
            systemContactRef: "file-backed-environment",
            displayName: "File-backed Contact"
        )
        let environment = try ProductionRepositoryFactory.makeFileBackedEnvironment(
            applicationSupportDirectory: root,
            fileName: fileName,
            fileManager: fileManager
        )
        let seededWindow = try await environment.window.fetchGlobal()
        var profile = try await environment.profile.fetch()
        profile.onboardingCompletedAt = onboardingDate
        try await environment.profile.save(profile)
        try await environment.contacts.upsert(contact)

        #expect(fileManager.fileExists(atPath: databaseURL.path))
        #if !targetEnvironment(simulator)
        // The simulator accepts the protection write but does not expose the
        // attribute on its host-backed filesystem. A device does, so keep the
        // value assertion on the platform where the OS enforces it; this test
        // still executes the exact production setter on every simulator run.
        let directoryAttributes = try fileManager.attributesOfItem(
            atPath: databaseURL.deletingLastPathComponent().path
        )
        #expect(
            directoryAttributes[.protectionKey] as? FileProtectionType
                == .completeUntilFirstUserAuthentication
        )
        #endif

        let reopened = try ProductionRepositoryFactory.makeFileBackedEnvironment(
            applicationSupportDirectory: root,
            fileName: fileName,
            fileManager: fileManager
        )
        let reopenedProfile = try await reopened.profile.fetch()
        #expect(reopenedProfile.onboardingCompletedAt == onboardingDate)
        #expect(try await reopened.window.fetchGlobal() == seededWindow)
        #expect(try await reopened.contacts.fetch(id: contact.id)?.displayName == contact.displayName)
    }

    @Test("Fresh latest schema has v2 columns and defaults")
    func freshLatestSchemaHasV2Defaults() async throws {
        let queue = try DatabaseFactory.makeInMemoryDatabase()

        let values = try await queue.write { db -> (String, String, String, Int, Int?) in
            try db.execute(
                sql: """
                    INSERT INTO Contact
                        (id, systemContactRef, displayName, preferredChannel, createdAt)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                arguments: [
                    UUID().uuidString,
                    "fresh-v2-contact",
                    "Fresh Contact",
                    Channel.phoneCall.rawValue,
                    1_700_000_000,
                ])

            guard let contact = try Row.fetchOne(
                db,
                sql: "SELECT phonesJson, emailsJson FROM Contact WHERE systemContactRef = ?",
                arguments: ["fresh-v2-contact"]
            ), let window = try Row.fetchOne(
                db,
                sql: "SELECT occasionTime, digestHorizonDays FROM ReminderWindow WHERE id = 1"
            ), let profile = try Row.fetchOne(
                db,
                sql: "SELECT trialStartedAt FROM UserProfile WHERE id = 1"
            ) else {
                throw DataError.notFound
            }

            let phones: String = contact["phonesJson"]
            let emails: String = contact["emailsJson"]
            let occasionTime: String = window["occasionTime"]
            let horizon: Int = window["digestHorizonDays"]
            let trialStartedAt: Int? = profile["trialStartedAt"]
            return (phones, emails, occasionTime, horizon, trialStartedAt)
        }

        #expect(values.0 == "[]")
        #expect(values.1 == "[]")
        #expect(values.2 == "09:00")
        #expect(values.3 == 14)
        #expect(values.4 == nil)
    }

    @Test("v1 upgrades to v2 without losing rows and normalizes JSON null (R39)")
    func v1UpgradesToV2() async throws {
        let queue = try DatabaseQueue()
        let migrator = RegardsSchema.migrator()
        try migrator.migrate(queue, upTo: "v1")

        let groupId = UUID(uuidString: "10000000-0000-0000-0000-000000000001")!
        let contactId = UUID(uuidString: "20000000-0000-0000-0000-000000000002")!
        let reminderId = UUID(uuidString: "30000000-0000-0000-0000-000000000003")!
        let interactionId = UUID(uuidString: "40000000-0000-0000-0000-000000000004")!

        try await queue.write { db in
            try db.execute(
                sql: """
                    INSERT INTO ContactGroup
                        (id, displayName, primaryContactId, createdAt, createdBy)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                arguments: [
                    groupId.uuidString,
                    "Legacy Household",
                    contactId.uuidString,
                    1_699_999_900,
                    ContactGroup.Origin.user.rawValue,
                ])
            try db.execute(
                sql: """
                    INSERT INTO Contact
                        (id, systemContactRef, displayName, tracked, preferredChannel,
                         contactGroupId, createdAt)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                arguments: [
                    contactId.uuidString,
                    "legacy-contact",
                    "Legacy Contact",
                    true,
                    Channel.email.rawValue,
                    groupId.uuidString,
                    1_700_000_000,
                ])
            try db.execute(
                sql: """
                    INSERT INTO ScheduledReminder
                        (id, contactId, kind, occasionDate, occasionLabel,
                         scheduledFor, osNotificationId, state)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                arguments: [
                    reminderId.uuidString,
                    contactId.uuidString,
                    ReminderKind.cadence.rawValue,
                    nil,
                    nil,
                    1_700_000_100,
                    "legacy-notification",
                    ReminderState.pending.rawValue,
                ])
            try db.execute(
                sql: """
                    INSERT INTO InteractionLog
                        (id, contactId, occurredAt, source, channel)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                arguments: [
                    interactionId.uuidString,
                    contactId.uuidString,
                    1_700_000_200,
                    InteractionSource.manual.rawValue,
                    Channel.email.rawValue,
                ])
            try db.execute(
                sql: "UPDATE ReminderWindow SET quietHoursJson = 'null' WHERE id = 1")
            try db.execute(
                sql: """
                    UPDATE UserProfile
                    SET onboardingCompletedAt = ?, entitlementTier = ?, entitlementRefreshedAt = ?
                    WHERE id = 1
                    """,
                arguments: [
                    1_700_000_300,
                    EntitlementTier.trial.rawValue,
                    1_700_000_400,
                ])
        }

        try migrator.migrate(queue)

        let values = try await queue.read { db ->
            (String, String, String, String, Int, Int?, String?) in
            guard let contact = try Row.fetchOne(
                db,
                sql: "SELECT displayName, phonesJson, emailsJson FROM Contact WHERE systemContactRef = ?",
                arguments: ["legacy-contact"]
            ), let window = try Row.fetchOne(
                db,
                sql: """
                    SELECT quietHoursJson, occasionTime, digestHorizonDays
                    FROM ReminderWindow WHERE id = 1
                    """
            ), let profile = try Row.fetchOne(
                db,
                sql: "SELECT trialStartedAt FROM UserProfile WHERE id = 1"
            ) else {
                throw DataError.notFound
            }

            let name: String = contact["displayName"]
            let phones: String = contact["phonesJson"]
            let emails: String = contact["emailsJson"]
            let occasionTime: String = window["occasionTime"]
            let horizon: Int = window["digestHorizonDays"]
            let trialStartedAt: Int? = profile["trialStartedAt"]
            let quietHours: String? = window["quietHoursJson"]
            return (name, phones, emails, occasionTime, horizon, trialStartedAt, quietHours)
        }

        #expect(values.0 == "Legacy Contact")
        #expect(values.1 == "[]")
        #expect(values.2 == "[]")
        #expect(values.3 == "09:00")
        #expect(values.4 == 14)
        #expect(values.5 == nil)
        #expect(values.6 == nil)

        let repositories = GRDBRepositories(dbQueue: queue)
        let contact = try await repositories.contacts.fetch(id: contactId)
        let group = try await repositories.groups.fetch(id: groupId)
        let reminders = try await repositories.reminders.fetchAllPending()
        let interactions = try await repositories.interactions.fetchRecent(
            forContact: contactId,
            limit: 10
        )
        let window = try await repositories.window.fetchGlobal()
        let profile = try await repositories.profile.fetch()

        #expect(contact?.contactGroupId == groupId)
        #expect(contact?.phoneNumbers == [])
        #expect(contact?.emailAddresses == [])
        #expect(group?.displayName == "Legacy Household")
        #expect(group?.primaryContactId == contactId)
        #expect(reminders.map(\.id) == [reminderId])
        #expect(interactions.map(\.id) == [interactionId])
        #expect(interactions.first?.channel == .email)
        #expect(window.quietHours == nil)
        #expect(window.occasionTime == TimeOfDay(hour: 9))
        #expect(window.digestHorizonDays == 14)
        #expect(profile.onboardingCompletedAt == Date(timeIntervalSince1970: 1_700_000_300))
        #expect(profile.entitlementTier == .trial)
        #expect(profile.entitlementRefreshedAt == Date(timeIntervalSince1970: 1_700_000_400))
        #expect(profile.trialStartedAt == nil)
    }

    @Test("v1 upgrade preserves a legacy contact override and non-null quiet hours")
    func v1UpgradePreservesLegacyWindowJSON() async throws {
        let queue = try DatabaseQueue()
        let migrator = RegardsSchema.migrator()
        try migrator.migrate(queue, upTo: "v1")

        let contactID = try #require(
            UUID(uuidString: "50000000-0000-0000-0000-000000000005")
        )
        let override = ReminderWindow(
            allowedDays: .weekends,
            allowedTimeRanges: [
                TimeRange(start: TimeOfDay(hour: 10), end: TimeOfDay(hour: 12)),
            ],
            quietHours: nil,
            timezoneIdentifier: "Asia/Kolkata"
        )
        let quietHours = TimeRange(
            start: TimeOfDay(hour: 22, minute: 30),
            end: TimeOfDay(hour: 7, minute: 30)
        )
        let encoder = JSONEncoder()
        let encodedOverride = try encoder.encode(override)
        guard var legacyObject = try JSONSerialization.jsonObject(with: encodedOverride)
            as? [String: Any] else {
            throw DataError.invalidJSONEncoding
        }
        legacyObject.removeValue(forKey: "occasionTime")
        legacyObject.removeValue(forKey: "digestHorizonDays")
        let legacyData = try JSONSerialization.data(withJSONObject: legacyObject)
        let quietData = try encoder.encode(quietHours)
        guard let legacyJSON = String(data: legacyData, encoding: .utf8),
              let quietJSON = String(data: quietData, encoding: .utf8) else {
            throw DataError.invalidJSONEncoding
        }

        try await queue.write { db in
            try db.execute(
                sql: """
                    INSERT INTO Contact
                        (id, systemContactRef, displayName, tracked, preferredChannel,
                         reminderWindowOverride, createdAt)
                    VALUES (?, ?, ?, ?, ?, ?, ?)
                    """,
                arguments: [
                    contactID.uuidString,
                    "legacy-window-contact",
                    "Legacy Window Contact",
                    true,
                    Channel.phoneCall.rawValue,
                    legacyJSON,
                    1_700_000_000,
                ]
            )
            try db.execute(
                sql: "UPDATE ReminderWindow SET quietHoursJson = ? WHERE id = 1",
                arguments: [quietJSON]
            )
        }

        try migrator.migrate(queue)

        let repositories = GRDBRepositories(dbQueue: queue)
        let loadedContact = try #require(try await repositories.contacts.fetch(id: contactID))
        let loadedOverride = try #require(loadedContact.reminderWindowOverride)
        let loadedGlobal = try await repositories.window.fetchGlobal()

        #expect(loadedOverride.allowedDays == override.allowedDays)
        #expect(loadedOverride.allowedTimeRanges == override.allowedTimeRanges)
        #expect(loadedOverride.timezoneIdentifier == override.timezoneIdentifier)
        #expect(loadedOverride.occasionTime == ReminderWindow.defaultOccasionTime)
        #expect(loadedOverride.digestHorizonDays == ReminderWindow.defaultDigestHorizonDays)
        #expect(loadedGlobal.quietHours == quietHours)
    }

    @Test("A Contact round-trips through the GRDB repository")
    func contactRoundTrip() async throws {
        let queue = try DatabaseFactory.makeInMemoryDatabase()
        let repo = GRDBRepositories(dbQueue: queue).contacts

        let original = Contact(
            systemContactRef: "sys-test-1",
            displayName: "Priya Raghavan",
            tracked: true,
            cadenceDays: 14,
            priorityTier: .innerCircle,
            preferredChannel: .whatsapp,
            preferredChannelValue: "+919876543210",
            phoneNumbers: ["+919876543210", "+919876543211"],
            emailAddresses: ["priya@example.com", "priya@work.example"],
            reminderWindowOverride: ReminderWindow(
                allowedDays: .weekends,
                allowedTimeRanges: [
                    TimeRange(start: TimeOfDay(hour: 10), end: TimeOfDay(hour: 12)),
                ],
                timezoneIdentifier: "Asia/Kolkata",
                occasionTime: TimeOfDay(hour: 8, minute: 15),
                digestHorizonDays: 30),
            lastInteractedAt: Date(timeIntervalSince1970: 1_700_000_000),
            notes: "Test notes")

        try await repo.upsert(original)
        let loaded = try await repo.fetch(id: original.id)

        #expect(loaded?.displayName == original.displayName)
        #expect(loaded?.tracked == true)
        #expect(loaded?.cadenceDays == 14)
        #expect(loaded?.priorityTier == .innerCircle)
        #expect(loaded?.preferredChannel == .whatsapp)
        #expect(loaded?.preferredChannelValue == "+919876543210")
        #expect(loaded?.phoneNumbers == original.phoneNumbers)
        #expect(loaded?.emailAddresses == original.emailAddresses)
        #expect(loaded?.reminderWindowOverride == original.reminderWindowOverride)
        #expect(loaded?.notes == "Test notes")
        #expect(loaded?.lastInteractedAt == original.lastInteractedAt)
    }

    @Test("v2 ReminderWindow and UserProfile fields round-trip")
    func v2SingletonFieldsRoundTrip() async throws {
        let queue = try DatabaseFactory.makeInMemoryDatabase()
        let repositories = GRDBRepositories(dbQueue: queue)
        let window = ReminderWindow(
            allowedDays: .allDays,
            allowedTimeRanges: [
                TimeRange(start: TimeOfDay(hour: 8), end: TimeOfDay(hour: 11)),
            ],
            quietHours: nil,
            timezoneIdentifier: "America/Los_Angeles",
            occasionTime: TimeOfDay(hour: 7, minute: 45),
            digestHorizonDays: 30)
        let trialStartedAt = Date(timeIntervalSince1970: 1_800_000_000)
        let profile = UserProfile(
            onboardingCompletedAt: Date(timeIntervalSince1970: 1_800_000_100),
            entitlementTier: .trial,
            entitlementRefreshedAt: Date(timeIntervalSince1970: 1_800_000_200),
            trialStartedAt: trialStartedAt)

        try await repositories.window.saveGlobal(window)
        try await repositories.profile.save(profile)

        let loadedWindow = try await repositories.window.fetchGlobal()
        let loadedProfile = try await repositories.profile.fetch()
        #expect(loadedWindow == window)
        #expect(loadedProfile == profile)
    }

    @Test("Reminder can be written and read back, state update persists")
    func reminderRoundTripAndStateUpdate() async throws {
        let queue = try DatabaseFactory.makeInMemoryDatabase()
        let repos = GRDBRepositories(dbQueue: queue)

        let contact = Contact(
            systemContactRef: "sys-test-2",
            displayName: "Mom",
            tracked: true, cadenceDays: 7,
            priorityTier: .innerCircle,
            preferredChannel: .phoneCall, preferredChannelValue: "+14155550134")
        try await repos.contacts.upsert(contact)

        let reminder = ScheduledReminder(
            contactId: contact.id,
            kind: .cadence,
            scheduledFor: Date(timeIntervalSince1970: 1_800_000_000),
            osNotificationId: "iosid-1")
        try await repos.reminders.upsert(reminder)

        let pending = try await repos.reminders.fetchAllPending()
        #expect(pending.count == 1)
        try await repos.reminders.updateState(id: reminder.id, state: .userCaughtUp)
        let pendingAfter = try await repos.reminders.fetchAllPending()
        #expect(pendingAfter.isEmpty)
    }
}
